export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const MODIFICATE_PRODUCT = 'MODIFICATE_PRODUCT'


export const ADD_ORDER = 'ADD_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'
export const MODIFICATE_ORDER = 'MODIFICATE_ORDER'
